#! /bin/bash

# --------------------------------------------------------------------
function check_cmd {
  if ! type -P "$1" >/dev/null 2>&1; then
    echo "missing program: $1. install it first" >&2
    exit 1
  fi
}

check_cmd git
check_cmd m4
check_cmd autoconf
check_cmd gcc
check_cmd g++
check_cmd curl

# --------------------------------------------------------------------
if [ -e easycrypt ]; then
  echo "a file or directory [easycrypt] already exists" >&2
  echo "remove it first and restart this script" >&2
  exit 1
fi

# --------------------------------------------------------------------
set -ex

git clone http://ci.easycrypt.info/easycrypt.git easycrypt

make -C easycrypt toolchain provers
$(easycrypt/scripts/active-toolchain.sh)
make -C easycrypt
