# -*- Makefile -*-

# --------------------------------------------------------------------
.PHONY: default linux macos clean

# --------------------------------------------------------------------
default:
	@echo "make [linux|macos]"

linux:
	scripts/build-linux.sh

macos:
	scripts/build-macos.sh

clean:
	rm -rf _build
