#! /usr/bin/env python

# --------------------------------------------------------------------
import sys, os

# --------------------------------------------------------------------
EMACS = dict(
    darwin = 'share/Emacs.app/Contents/MacOS/Emacs',
    win32  = 'share/emacs/bin/emacs.exe',
)

# --------------------------------------------------------------------
def _main():
    mydir = os.path.realpath(os.path.dirname(__file__))
    emacs = 'emacs'
    args  = []

    if sys.platform == 'darwin':
        emacs = os.path.join(mydir, *EMACS['darwin'].split('/'))
    if sys.platform == 'cygwin' or sys.platform.startswith('win'):
        emacs = os.path.join(mydir, *EMACS['win32'].split('/'))

    args.extend(['-l', 'share/easycrypt/pg/emacs.rc'])
    args.extend(['--no-init-file', '--no-site-file', '--debug-init'])

    print >>sys.stderr, 'running: %s' % (' '.join([emacs] + args))

    os.chdir(mydir)
    os.putenv('PATH', '%s%s%s' % (os.path.join(mydir, 'bin'), \
                                  os.pathsep, \
                                  os.environ.get('PATH', '')))
    try:
        os.execvp(emacs, [emacs] + args)
    except OSError as e:
        print >>sys.stderr, 'cannot run Emacs: %s' % (repr(e,))
        sys.exit(1)

# --------------------------------------------------------------------
if __name__ == '__main__':
    _main()
