#!/bin/sh

# To launch EasyCrypt tool

# Copy ec.init in .ocamlinit so it is loaded automatically :
EC_PATH=`dirname $0`
EC_INIT=$EC_PATH/ec.init
OCAMLINIT=./.ocamlinit
echo "Copying $EC_INIT --> $OCAMLINIT"
cp $EC_INIT $OCAMLINIT

# try to use 'ledit'
LEDIT=`which ledit`
echo "Using ledit --> $LEDIT"
# LEDIT and PROOFGENERAL don't mix well together
# $LEDIT $EC_PATH/easycrypt.top $*
$EC_PATH/easycrypt.top $*

