FROM easycryptpa/ec-build-box:latest

RUN \
	sudo apt-get -q -y install \
	  texlive-base \
	  texlive-binaries \
	  texlive-extra-utils \
	  texlive-font-utils \
	  texlive-fonts-extra \
	  texlive-fonts-recommended \
	  texlive-generic-recommended \
	  texlive-latex-base \
	  texlive-latex-extra \
	  texlive-latex-recommended \
	  texlive-math-extra \
	&& sudo apt-get -q -y clean
