EMACS=$(shell if [ -z "`which emacs`" ]; then echo "Emacs executable not found"; exit 1; else echo emacs; fi)

PREFIX=/usr

DIRECTORY=certicrypt

ELISPP=${PREFIX}/share/${EMACS}/site-lisp/ProofGeneral

PROOFSITE=${ELISPP}/generic/proof-site.el

install:
	@(if [ ! -d "$$DIRECTORY" ]; then \
	 mkdir -p ${ELISPP}/${DIRECTORY}; \
	fi; \
	cp -pf certicrypt/*.el ${ELISPP}/${DIRECTORY}; \
	if ! grep -q certicrypt ${PROOFSITE}; then \
  	  sed -i -e '/\([^)]\)(phox "PhoX" "phx")/{x;s/$$/      (certicrypt "CertiCrypt" "ec" nil (".v" ".vo" ".glob" ".ml"))/;G;}' ${PROOFSITE}; \
	fi;)
