name: check-contributions
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Container setup
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Cachix setup (push)
        uses: cachix/cachix-action@v10
        with:
          name: formosa-crypto
          authToken: '${{ secrets.CACHIX_WRITE_TOKEN }}'
      - name: Fetch EC source
        if: github.event_name == 'push'
        uses: actions/checkout@v3
      - name: Build binaries
        if: github.event_name == 'push'
        run: |
          export NIXPKGS_ALLOW_UNFREE=1
          cd "${{ github.workspace }}/scripts/nix"
          nix-build z3.nix \
            --arg    lib                 "(import <nixpkgs> {}).lib" \
            --arg    stdenv              "(import <nixpkgs> {}).stdenv" \
            --arg    fetchFromGitHub     "(import <nixpkgs> {}).fetchFromGitHub" \
            --arg    python              "(import <nixpkgs> {}).python3" \
            --arg    fixDarwinDylibNames "(import <nixpkgs> {}).fixDarwinDylibNames" \
            --arg    writeScript         "(import <nixpkgs> {}).writeScript" \
            --argstr version             "4.8.10"
          nix-build easycrypt.nix --argstr ecRev "$GITHUB_SHA"
  check:
    needs: build
    runs-on: ubuntu-latest
    environment: actions
    strategy:
      matrix:
        contribs:
          - name: "jasmin-eclib-release"
            url: "https://github.com/jasmin-lang/jasmin.git"
            branch: "release-21"
            workdir: "eclib"
            config: "tests.config"
            checks: [ "jasmin" ]
          - name: "jasmin-eclib-main"
            url: "https://github.com/jasmin-lang/jasmin.git"
            branch: "main"
            workdir: "eclib"
            config: "tests.config"
            checks: [ "jasmin" ]
          - name: "sha3"
            url: "https://gitlab.com/easycrypt/sha3.git"
            branch: "master"
            workdir: "."
            config: "config/tests.config"
            checks: [ "sponge" ]
    steps:
      - name: Container setup
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Cachix setup
        uses: cachix/cachix-action@v10
        with:
          name: formosa-crypto
      - name: Fetch EC source
        uses: actions/checkout@v3
      - name: Install binaries
        run: |
          export NIXPKGS_ALLOW_UNFREE=1
          cd ${{ github.workspace }}/scripts/nix
          nix-env --install --file z3.nix \
            --arg    lib                 "(import <nixpkgs> {}).lib" \
            --arg    stdenv              "(import <nixpkgs> {}).stdenv" \
            --arg    fetchFromGitHub     "(import <nixpkgs> {}).fetchFromGitHub" \
            --arg    python              "(import <nixpkgs> {}).python3" \
            --arg    fixDarwinDylibNames "(import <nixpkgs> {}).fixDarwinDylibNames" \
            --arg    writeScript         "(import <nixpkgs> {}).writeScript" \
            --argstr version             "4.8.10"
          nix-env --install --file easycrypt.nix --argstr ecRev "$GITHUB_SHA"
          nix-env --install gnumake why3 alt-ergo cvc4 --file '<nixpkgs>'
      - name: Configure EasyCrypt
        run: |
          mkdir -p ~/.config/easycrypt
          easycrypt why3config
          easycrypt config
      - name: Checkout contrib
        run: |
          git clone --branch ${{ matrix.contribs.branch }} ${{ matrix.contribs.url }} ${{ github.workspace }}/${{ matrix.contribs.name }}
      - name: Check contrib
        run: |
          cd ${{ github.workspace }}/${{ matrix.contribs.name }}/${{ matrix.contribs.workdir }}
          ec-runtest ${{ matrix.contribs.config }} ${{ matrix.config.checks }} --report=${{ matrix.contribs.name }}.xml
