name: EasyCrypt compilation & check

on: [push,pull_request]

jobs:
  compile-opam:
    name: EasyCrypt compilation (opam)
    runs-on: ubuntu-20.04
    container:
      image: easycryptpa/ec-build-box
      options: --user root
    steps:
    - uses: actions/checkout@v2
    - name: Set ownership
      run: |
        sudo chown opam:opam -R .
        sudo chown opam:opam -R ~
    - name: Update OPAM & EasyCrypt dependencies
      run: |
        sudo -u opam opam update
        sudo -u opam opam pin add -n easycrypt .
        sudo -u opam opam install --deps-only easycrypt
    - name: Compile EasyCrypt
      run: sudo -u opam opam config exec -- make

  compile-nix:
    name: EasyCrypt compilation (nix)
    runs-on: ubuntu-20.04
    steps:
    - name: Fetch EC source
      uses: actions/checkout@v3
    - name: Setup Nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Cachix setup
      uses: cachix/cachix-action@v10
      with:
        name: formosa-crypto
        authToken: '${{ secrets.CACHIX_WRITE_TOKEN }}'
    - name: Build and cache EasyCrypt and dependencies
      run: |
        nix-build ./scripts/nix/easycrypt.nix --argstr ecRev ${{ github.sha }}

  check:
    name: Check EasyCrypt Libraries
    needs: compile-opam
    runs-on: ubuntu-20.04
    container:
      image: easycryptpa/ec-build-box
      options: --user root
    strategy:
      fail-fast: false
      matrix:
        target: [stdlib, examples]
    steps:
    - uses: actions/checkout@v2
    - name: Set ownership
      run: |
        sudo chown opam:opam -R .
        sudo chown opam:opam -R ~
    - name: Update OPAM & EasyCrypt dependencies
      run: |
        sudo -u opam opam update
        sudo -u opam opam pin add -n easycrypt .
        sudo -u opam opam install --deps-only easycrypt
    - name: Compile EasyCrypt
      run: sudo -u opam opam config exec -- make
    - name: Detect SMT provers
      run: |
        sudo -u opam rm -f ~/.why3.conf
        sudo -u opam opam config exec -- ./ec.native why3config -why3 ~/.why3.conf
    - name: Compile Library (${{ matrix.target }})
      env:
        TARGET: ${{ matrix.target }}
      run: sudo -u opam opam config exec -- make $TARGET
    - uses: actions/upload-artifact@v2
      name: Upload report.log
      if: always()
      with:
        name: report.log (${{ matrix.target }})
        path: report.log
        if-no-files-found: ignore

  notification:
    name: Notification
    needs: [compile-opam, compile-nix, check]
    if: |
      (github.event_name == 'push') ||
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
    runs-on: ubuntu-20.04
    steps:
    - uses: technote-space/workflow-conclusion-action@v2
    - uses: zulip/github-actions-zulip/send-message@v1
      with:
        api-key: ${{ secrets.ZULIP_APIKEY }}
        email: ${{ secrets.ZULIP_EMAIL }}
        organization-url: 'https://formosa-crypto.zulipchat.com'
        type: 'stream'
        to: 'GitHub notifications'
        topic: 'EasyCrypt / CI'
        content: |
          **Build status**: ${{ env.WORKFLOW_CONCLUSION }} ${{ env.WORKFLOW_CONCLUSION == 'success' && ':check_mark:' || ':cross_mark:' }}
          **Author**: [${{ github.actor }}](${{ github.server_url }}/${{ github.actor }})
          **Event**: ${{ github.event_name }} on ${{ github.ref }}
          **Commit**: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
          **Details**: [Build log](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}/checks)
