name: EasyCrypt Docker Containers Build

on:
  push:
    branches:
      - 'main'
      - 'release'
    tags:
      - 'r[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  make-images:
    name: Build and Push Container Images
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    env:
      TAG: ${{ github.ref_name }}
    steps:
    - uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push `base` Image
      env:
        VARIANT: base
      run: |
        make -C scripts/docker build publish

    - name: Build and push `build` Image
      env:
        VARIANT: build
      run: |
        make -C scripts/docker build publish

    - name: Build and push `formosa` Image
      env:
        VARIANT: formosa
      run: |
        make -C scripts/docker build publish

    - name: Build and push `test` Image
      if: github.ref_name != 'main'
      env:
        VARIANT: test
      run: |
        make -C scripts/docker build publish
